name: Android CI

on:
  push:
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Set up JDK 18
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Give permission to executable
        run: chmod +x gradlew
        
      - name: Clean with gradle
        uses: gradle/gradle-build-action@v2.3.0
        with:
          gradle-version: 7.5.1
          arguments: clean

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2.3.0
        with:
          android-gradle-plugin: 7.4.0
          gradle-version: 7.5.1
          arguments: assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v3.1.0
        if: ${{ !github.head_ref }}
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
