---
name: Code Formatter

on:
  workflow_dispatch:

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
 
      - name: Set up JDK 18
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Format Java Source
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: javaFormat

      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--aosp --replace"
          commitMessage: "Format Java Code"
